Research.Eng: Soft.Eng MS
	@echo Research.Eng
IVF.spec: Gynic MD
	@echo MD
Soft.Eng: IIT
	@echo Soft.Eng
MS: IIT
	@echo MS
Hard.Eng: NIT
	@echo Hard.Eng
Gynic: AIIMS
	@echo Gynic
ENT: AIIMS
	@echo ENT
MD: AIIMS
	@echo MD
Dentist: CMC
	@echo Dentist
IIT: JEE
	@echo IIT
NIT: JEE
	@echo NIT
AIIMS: NEET
	@echo AIIMS
CMC: NEET
	@echo CMC
JEE: MPC
	@echo JEE
NEET: BiPC
	@echo NEET
MPC: school
	@echo MPC
BiPC: school
	@echo BiPC
school:
	@echo school